.\" SPDX-FileCopyrightText: 2026 Julien Y. Dutheil <dutheil@evolbio.mpg.de>
.\"
.\" SPDX-License-Identifier: CC-BY-4.0

.TH BPPPHYSAMP 1 LOCAL

.SH NAME

bppphysamp - Phylogenetic Sampling

.SH SYNOPSIS

.B bppphysamp [options]

.SH AVAILABILITY

All UNIX flavors

.SH DESCRIPTION

bppphysamp samples a sequence alignment according to a given phylogenetic tree, in order to control the set of redundancy in the data.

.SH OPTIONS

You should refer to 'info physamp' or to the online manual of bppsuite for a complete list of available options.

.TP 5

--noninteractive

generates output for redirection in a file.

.TP

param=file

reads a file for loading options

.SH AUTHOR

Julien Y. Dutheil.
